@include('v2.layouts.1col', collect()
    ->put('header', region('StaticHeader', collect()
        ->push(component('Title')
            ->is('red')
            ->is('large')
            ->with('title', trans(auth()->check()
                ? 'error.401.title.logged' : 'error.401.title.unlogged'
            ))
        )
    ))
    ->put('content', collect()
        ->push(component('Body')
            ->is('responsive')
            ->with('body', trans(auth()->check()
                ? 'error.401.body.logged' : 'error.401.body.unlogged'
            ))        )
        ->push('&nbsp;')
    )
    ->put('footer', region('FooterLight'))
)