<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateNewsletterLetters extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('newsletter_letters', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name'); // Nädala uudiskiri 14.08 - 21.08 - auto generated by system
            $table->integer('newsletter_type_id')->unsigned()->index();
            $table->timestamps();

            $table->foreign('newsletter_type_id')->references('id')->on('newsletter_types')
                ->onUpdate('cascade')->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('newsletter_letters');
    }
}
