<?php

namespace App\Http\Controllers;

class V2AuthController extends Controller
{
    public function loginFormExperiment()
    {
        return layout('1colnarrow')
            ->with('color', 'gray')
            ->with('background', component('BackgroundMap'))
            ->with('header', region('StaticHeader'))

            ->with('top', collect()
                ->push(component('Title')
                    ->is('center')
                    ->is('large')
                    ->with('title', trans('auth.login.title'))
                )
                ->push('&nbsp;')
                ->push(component('Title')
                    ->is('center')
                    ->is('small')
                    ->with('title', trans('auth.login.not.registered'))
                )
            )

            ->with('content_top', component('Grid3')->with('items', collect()
                ->push(component('AuthTab')
                    ->with('title', trans('auth.login.field.name.title'))
                )
                ->push(component('AuthTab')
                    ->is('facebook')
                    ->with('route', route('facebook.redirect'))
                    ->with('title', 'Facebook')
                )
                ->push(component('AuthTab')
                    ->is('google')
                    ->with('route', route('google.redirect'))
                    ->with('title', 'Google')
                )
            ))

            ->with('content', collect()
                ->push(component('Form')->with('fields', collect()
                    ->push(component('FormTextfield')
                        ->is('large')
                        ->with('title', trans('auth.login.field.name.title'))
                    )
                    ->push(component('FormPassword')
                        ->is('large')
                        ->with('title', trans('auth.login.field.password.title'))
                    )
                    ->push(component('FormCheckbox')
                        ->with('name', 'remember')
                        ->with('title', trans('auth.login.field.remember.title'))
                    )
                    ->push(component('FormButton')
                        ->is('wide')
                        ->with('title', trans('auth.login.submit.title'))
                    )
                ))
            )

            ->with('bottom', collect()->push(component('MetaLink')
                ->with('title', 'Ei mäleta parooli? Taasta parool siin')
            ))

            ->with('footer', region('FooterLight'))

            ->render();
    }

    public function registerFormExperiment()
    {
        return layout('1colnarrow')
            ->with('color', 'gray')
            ->with('background', component('BackgroundMap'))
            ->with('header', region('StaticHeader'))

            ->with('top', collect()
                ->push(component('Title')
                    ->is('center')
                    ->is('large')
                    ->with('title', trans('Registreeri'))
                )
                ->push('&nbsp;')
                ->push(component('Title')
                    ->is('center')
                    ->is('small')
                    ->with('title', trans('Liitu Trip.ee reisihuviliste seltskonnaga'))
                )
            )

            ->with('content_top', component('Grid3')->with('items', collect()
                ->push(component('AuthTab')
                    ->with('title', 'E-mailiga')
                )
                ->push(component('AuthTab')
                    ->is('facebook')
                    ->with('title', 'Facebook')
                )
                ->push(component('AuthTab')
                    ->is('google')
                    ->with('title', 'Google')
                )
            ))

            ->with('content', collect()
                ->push(component('Form')->with('fields', collect()
                    ->push(component('FormTextfield')
                        ->is('large')
                        ->with('title', 'Kasutajanimi')
                    )
                    ->push(component('FormTextfield')
                        ->is('large')
                        ->with('title', 'E-mail')
                    )
                    ->push(component('FormPassword')
                        ->is('large')
                        ->with('title', 'Parool')
                    )
                    ->push(component('FormPassword')
                        ->is('large')
                        ->with('title', 'Parool uuesti')
                    )
                    ->push(component('FormButton')
                        ->is('wide')
                        ->with('title', 'Registreeri')
                    )
                ))
            )

            ->with('bottom', collect()->push(component('MetaLink')
                ->with('title', 'Trip.ee keskkonnaga liitudes nõustun ma kasutajatingimustega')
            ))

            ->with('footer', region('FooterLight'))

            ->render();
    }

    public function passwordFormExperiment()
    {
        return layout('1colnarrow')
            ->with('color', 'gray')
            ->with('background', component('BackgroundMap'))
            ->with('header', region('StaticHeader'))

            ->with('top', collect()
                ->push(component('Title')
                    ->is('center')
                    ->is('large')
                    ->with('title', 'Ei mäleta oma parooli?')
                )
                ->push('&nbsp;')
                ->push(component('Title')
                    ->is('center')
                    ->is('small')
                    ->with('title', 'Sisesta oma e-mail ja me saadame sulle kinnituslingi')
                )
            )

            ->with('content', collect()
                ->push(component('Form')->with('fields', collect()
                    ->push(component('FormTextfield')
                        ->is('large')
                        ->with('title', 'Sinu e-post')
                    )
                    ->push(component('FormButton')
                        ->is('wide')
                        ->with('title', 'Saada')
                    )
                ))
            )

            ->with('bottom', collect()->push(component('MetaLink')
                ->with('title', 'Tuli meelde? Logi sisse siit.')
            ))

            ->with('footer', region('FooterLight'))

            ->render();
    }

    public function resetFormExperiment()
    {
        return layout('1colnarrow')
            ->with('color', 'gray')
            ->with('background', component('BackgroundMap'))
            ->with('header', region('StaticHeader'))

            ->with('top', collect()
                ->push(component('Title')
                    ->is('center')
                    ->is('large')
                    ->with('title', 'Vali uus parool')
                )
            )

            ->with('content', collect()
                ->push(component('Form')->with('fields', collect()
                    ->push(component('FormTextfield')
                        ->is('large')
                        ->with('title', 'Sinu e-post')
                    )
                    ->push(component('FormPassword')
                        ->is('large')
                        ->with('title', 'Uus parool')
                    )
                    ->push(component('FormPassword')
                        ->is('large')
                        ->with('title', 'Korda parooli')
                    )
                    ->push(component('FormButton')
                        ->is('wide')
                        ->with('title', 'Kinnita')
                    )
                ))
            )

            ->with('footer', region('FooterLight'))

            ->render();
    }
}
